name: Release and Hash
description: Upload files to GitHub Release and attach file hash to asset urls.
inputs:
  tag:
    description: release tag
    required: true
  files:
    description: files to upload
    required: true
  repo:
    description: upload to which repo
    required: true
    default: ${{ github.repository }}
outputs:
  urls:
    description: url to uploaded files, with sha256 as url fragment
    value: ${{ steps.hash.outputs.urls }}

runs:
  using: composite
  steps:
    - name: upload
      run: |
        gh release -R ${{ inputs.repo }} view ${{ inputs.tag }} --json url > /dev/null
        if [ $? ]; then
            gh release -R ${{ inputs.repo }} upload --clobber ${{ inputs.tag }} ${{ inputs.files }}
        else
            gh release -R ${{ inputs.repo }} create ${{ inputs.tag }} ${{ inputs.files }}
        fi
      shell: bash

    - name: query urls
      id: query
      run: |
        sharp_list="#"
        for file in $(ls ${{ inputs.files }}); do
            sharp_list="$sharp_list$(basename $file)#"
        done

        filter=".assets[] | select( \"#\" + .name + \"#\" | inside(\"$sharp_list\") ) | .url"
        urls=$(gh release -R ${{ inputs.repo }} view ${{ inputs.tag }} --json assets -q "$filter")

        echo "urls=$urls" >> $GITHUB_OUTPUT
      shell: bash

    - uses: ./.github/actions/url-attach-hash
      id: hash
      with:
        files: ${{ inputs.files }}
        urls: ${{ steps.query.outputs.urls }}
