name: Add Assets without Hash

on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        description: which project to add or update.
      urls:
        type: string
        description: asset urls. if a url has not hash fragment, it should not contain "#".
      index-branch:
        type: string
        description: Which branch to store the index htmls, default as `idx-pages`.
        required: false
        default: idx-pages

jobs:
  hash:
    runs-on: ubuntu-latest
    env:
      urls: ${{ inputs.urls }}
    outputs:
      urls: ${{ steps.hash.outputs.urls }}
    steps:
      - name: fetch assets and hash
        id: hash
        run: |
          hash_urls=""
          for url in $urls; do
              if [[ $url =~ "#" ]]; then
                  hash_urls="${hash_urls}${urls} "
              else
                  wget --no-clobber $url > /dev/null
                  hash=$(sha256sum $(basename $url))
                  hash=(${hash// / }[0])
                  hash_urls="${hash_urls}${url}#sha256=${hash} "
              fi
          done
          echo "urls=${hash_ruls}" >> $GITHUB_OUTPUT

  add:
    uses: ./.github/workflows/add.yml
    needs: hash
    with:
      project: ${{ inputs.project }}
      urls: ${{ needs.hash.outputs.urls }}
      index-branch: ${{ inputs.index-branch }}
