name: Add Assets without Hash

on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        description: project name
      urls:
        type: string
        description: asset urls (if a url has no hash fragment, it should not contain "#")
      index-branch:
        type: string
        description: index branch
        required: false
        default: idx-pages
      rebuild:
        type: boolean
        description: rebuild pages
        required: false
        default: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  hash:
    runs-on: ubuntu-latest
    permissions: {}
    env:
      urls: ${{ inputs.urls }}
    outputs:
      urls: ${{ steps.hash.outputs.urls }}
    steps:
      - name: fetch assets and hash
        id: hash
        run: |
          hash_urls=""
          for url in $urls; do
              if [[ $url =~ "#" ]]; then
                  hash_urls="${hash_urls}${urls} "
              else
                  wget --no-clobber $url > /dev/null
                  hash=$(sha256sum $(basename $url))
                  hash=(${hash// / }[0])
                  echo "::debug::${url}#sha256=${hash}"
                  hash_urls="${hash_urls}${url}#sha256=${hash} "
              fi
          done
          echo "urls=${hash_urls}" >> $GITHUB_OUTPUT

  add:
    uses: ./.github/workflows/add.yml
    needs: hash
    with:
      project: ${{ inputs.project }}
      urls: ${{ needs.hash.outputs.urls }}
      index-branch: ${{ inputs.index-branch }}
      rebuild: ${{ inputs.rebuild }}
