name: Remove Assets from Index

concurrency:
  group: index
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        description: project name
      files:
        type: string
        description: filenames
      index-branch:
        type: string
        description: index htmls hosting branch
        required: false
        default: idx-pages

jobs:
  add:
    runs-on: ubuntu-latest
    env:
      idx-checkout-path: index
    steps:
      - name: checkout script branch
        uses: actions/checkout@v3

      - name: checkout index branch
        uses: actions/checkout@v3
        with:
          path: ${{ env.idx-checkout-path }}
          ref: ${{ inputs.index-branch }}
          token: ${{ secrets.REPO_TOKEN || github.token }}

      - name: update simple index
        env:
          proj: ${{ inputs.project }}
          files: ${{ inputs.files }}
        run: |
          cd ${{ env.idx-checkout-path }}

          proj=$(echo ${proj} | tr "\-_." "-" | tr -s "-" | tr "A-Z" "a-z")
          proj_html="simple/${proj}/index.html"
          if [ ! -f $proj_html ]; then exit; fi

          for file in $files; do
              sed -i "/>${file}</ d" $proj_html
          done;

      - name: commit index changes
        run: |
          cd ${{ env.idx-checkout-path }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update project `${{ inputs.project }}`"
          git push
