name: Add Assets to Index

concurrency:
  group: index
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        description: which project to remove files from.
      files:
        type: string
        description: files to remove.
      repo:
        type: string
        description: Index hosting repository, default as caller repository.
        default: ${{ github.repository }}
      index-branch:
        type: string
        description: Which branch to store the index htmls, default as `idx-pages`.
        required: false
        default: idx-pages

jobs:
  add:
    runs-on: ubuntu-latest
    env:
      idx-checkout-path: index
    steps:
      - name: checkout script branch
        uses: actions/checkout@v3

      - name: checkout index branch
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          path: ${{ env.idx-checkout-path }}
          ref: ${{ inputs.index-branch }}
          token: ${{ secrets.REPO_TOKEN || github.token }}

      - name: update simple index
        env:
          proj: ${{ inputs.project }}
          files: ${{ inputs.files }}
        run: |
          cd ${{ env.idx-checkout-path }}

          proj_html="simple/${proj}/index.html"
          if [ ! -f $proj_html ]; then exit; fi

          for file in $files; do
              sed -i "/>${file}</ d" $proj_html
          done;

      - name: commit index changes
        run: |
          cd ${{ env.idx-checkout-path }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update project `${{ inputs.project }}`"
          git push

      - name: call deploy workflow
        uses: .github/workflows/publish.yml
